defaults:
  - _self_
hydra:
  run:  
    dir: ${logdir}
_target_: agent.eval.eval_reflow_agent.EvalReFlowAgent

name: ${env_name}_eval_reflow_mlp_ta${horizon_steps}_td${denoising_steps}
logdir: ${oc.env:DPPO_LOG_DIR}/gym/gym-eval/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
base_policy_path: /home/zhangtonghe/dppo/log/gym/gym-pretrain/hopper-medium-v2_pre_reflow_mlp_ta4_td20/2025-01-13_11-09-33_42/checkpoint/best.pt
#uniform: /home/zhangtonghe/dppo/log/gym/gym-pretrain/hopper-medium-v2_pre_reflow_mlp_ta4_td20/2025-01-13_11-09-33_42/checkpoint/best.pt
#logitnormal: /home/zhangtonghe/dppo/log/gym/gym-pretrain/hopper-medium-v2_pre_reflow_mlp_ta4_td20/2025-01-13_11-22-39_42/checkpoint/best.pt
#/home/zhangtonghe/dppo/log/gym-pretrain/gym-pretrain/hopper-medium-v2_pre_reflow_mlp_ta4_td20/2024-12-08_23-41-19_42/checkpoint/best.pt
# /home/zhangtonghe/dppo/log/gym-pretrain/gym-pretrain/hopper-medium-v2_pre_reflow_mlp_ta4_td20/2024-12-08_23-41-42_42/checkpoint/state_1500.pt
# /home/zhangtonghe/dppo/log/gym-pretrain/gym-pretrain/hopper-medium-v2_pre_reflow_mlp_ta4_td20/2024-12-08_23-41-19_42/checkpoint/best.pt
# /home/zhangtonghe/dppo/log/gym-pretrain/gym-pretrain/hopper-medium-v2_pre_reflow_mlp_ta4_td20/2024-12-08_23-41-42_42/checkpoint/state_1200.pt
# /home/zhangtonghe/dppo/log/gym-pretrain/gym-pretrain/hopper-medium-v2_pre_reflow_mlp_ta4_td20/2024-12-08_23-41-42_42/checkpoint/state_500.pt


normalization_path: ${oc.env:DPPO_DATA_DIR}/gym/${env_name}/normalization.npz

seed: 42
device: cuda:2
env_name: hopper-medium-v2
obs_dim: 11
action_dim: 3
denoising_steps: 20
cond_steps: 1
horizon_steps: 4
act_steps: 4


batch_size: 128

n_steps: 500  # each episode can take maximum (max_episode_steps / act_steps, =250 right now) steps but may finish earlier in gym. 
              # We only count episodes finished within n_steps for evaluation.
render_num: 0 # 0  positive if save_video, otherwise 0. 

env:
  n_envs: 50 # 10
  name: ${env_name}
  max_episode_steps: 1000
  reset_at_iteration: False
  save_video:  False #True # True only for robot mimic. 
  best_reward_threshold_for_success: 3  # success rate not relevant for gym tasks
  wrappers:
    mujoco_locomotion_lowdim:
      normalization_path: ${normalization_path}
    multi_step:
      n_obs_steps: ${cond_steps}
      n_action_steps: ${act_steps}
      max_episode_steps: ${env.max_episode_steps}
      reset_within_step: True

model:
  _target_: model.flow.reflow.ReFlow
  network:
    _target_: model.diffusion.mlp_diffusion.DiffusionMLP
    # network_path: ${base_policy_path}
    horizon_steps: ${horizon_steps}
    action_dim: ${action_dim}
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    time_dim: 128 #16 # 128
    mlp_dims: [512, 1025, 512] #[512, 512, 512]
    activation_type: ReLU
    out_activation_type: Identity
    use_layernorm: True #False
    residual_style: True
  device: ${device}
  horizon_steps: ${horizon_steps}
  action_dim: ${action_dim}
  act_min: -1
  act_max: 1 
  obs_dim: ${obs_dim}
  max_denoising_steps: ${denoising_steps}
  seed: ${seed}
  batch_size: ${batch_size}