defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.pretrain.train_reflow_agent.TrainReFlowAgent

name: ${env}_pre_reflow_mlp_ta${horizon_steps}_td${denoising_steps}
logdir: ${oc.env:DPPO_LOG_DIR}/gym/gym-pretrain/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}

train_dataset_path: ${oc.env:DPPO_DATA_DIR}/gym/${env}/train.npz

seed: 42
device: cuda:5
env: hopper-medium-v2

# future action forecasts
horizon_steps: 4
action_dim: 3

# observation history
cond_steps: 1
obs_dim: 11

# maximum denoising steps
denoising_steps: 20 # 128

batch_size: 128

train:
  n_epochs: 500 #3000
  batch_size: ${batch_size}
  learning_rate: 1e-3
  weight_decay: 1e-6
  lr_scheduler:
    first_cycle_steps: 3000
    warmup_steps: 1
    min_lr: 1e-4
  epoch_start_ema: 10
  update_ema_freq: 5
  save_model_freq: 100
  schedule_lr_each_grad_step: True  # False

wandb:
  entity: ${oc.env:DPPO_WANDB_ENTITY}
  project: gym-${env}-pretrain
  run: ${now:%H-%M-%S}_${name}

model:
  _target_: model.flow.reflow.ReFlow
  network:
    _target_: model.diffusion.mlp_diffusion.DiffusionMLP
    horizon_steps: ${horizon_steps}
    action_dim: ${action_dim}
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    time_dim: 128 #16
    mlp_dims: [512, 1024, 512] #[512, 512, 512]
    activation_type: ReLU
    out_activation_type: Identity
    use_layernorm: True # False
    residual_style: True
  device: ${device}
  horizon_steps: ${horizon_steps}
  action_dim: ${action_dim}
  act_min: -1
  act_max: 1 
  obs_dim: ${obs_dim}
  max_denoising_steps: ${denoising_steps}
  seed: ${seed}
  batch_size: ${batch_size}
  sample_t_type: logitnormal
ema:
  decay: 0.995

train_dataset:
  _target_: agent.dataset.sequence.StitchedSequenceDataset
  dataset_path: ${train_dataset_path}
  horizon_steps: ${horizon_steps}
  cond_steps: ${cond_steps}
  device: ${device}
  max_n_episodes: 2186 #200 #len(dataset["traj_lengths"]) =  2186, 2186 trajectories of different lengths in total. 