defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.pretrain.train_shortcutflow_agent.TrainShortCutFlowAgent

name: ${env}_pre_shortcutflow_mlp_ta${horizon_steps}_td${denoising_steps}
logdir: ${oc.env:DPPO_LOG_DIR}/gym-pretrain/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
train_dataset_path: ${oc.env:DPPO_DATA_DIR}/gym/${env}/train.npz

seed: 42
device: cpu
env: hopper-medium-v2

horizon_steps: 4
action_dim: 3
act_min: -1
act_max: 1

cond_steps: 1
obs_dim: 11

denoising_steps: 16

batch_size: 128
bootstrap_every: 4

wandb:
  entity: ${oc.env:DPPO_WANDB_ENTITY}
  project: gym-${env}-pretrain
  run: ${now:%H-%M-%S}_${name}

train:
  n_epochs: 500 #3000
  batch_size: ${batch_size}
  update_ema_freq: 5
  epoch_start_ema: 10
  save_model_freq: 10 #100
  #######################
  learning_rate: 1e-3
  weight_decay: 1e-6
  lr_scheduler:
    first_cycle_steps: 3000
    warmup_steps: 1
    min_lr: 1e-4
  #######################
  # train_split: 0.8   # percentage of train set in train+ validation. If not specified, then no validation is used. 
  # parallel: 1

model:
  _target_: model.flow.shortcut_flow.ShortCutFlow
  network:
    _target_: model.flow.mlp_flow.FlowMLP    # no visual inputs
    action_dim: ${action_dim}
    horizon_steps: ${horizon_steps}
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}   # for mujoco tasks, the condition is the stacked observation
    time_dim: 16    # the dimension of the embedding of t
    dt_base_dim: 16 # the dimension of the embedding of dt_base
    mlp_dims: [512, 512, 512]
    activation_type: ReLU
    out_activation_type: Identity
    use_layernorm: False
    residual_style: True
  device: ${device}
  horizon_steps: ${horizon_steps}
  action_dim: ${action_dim}
  act_min: ${act_min}
  act_max: ${act_max}
  obs_dim: ${obs_dim}
  max_denoising_steps: ${denoising_steps}
  batch_size: ${batch_size}
  bootstrap_every: ${bootstrap_every}
  seed: ${seed}

ema:
  decay: 0.995

train_dataset:
  _target_: agent.dataset.sequence.StitchedSequenceDataset
  dataset_path: ${train_dataset_path}
  horizon_steps: ${horizon_steps}
  cond_steps: ${cond_steps}
  device: ${device}
  max_n_episodes: 1000